server:
  port: 8301
spring:
  application:
    name: ACHUI-Gateway
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
eureka:
  instance:
    lease-expiration-duration-in-seconds: 20
  client:
    register-with-eureka: true
    fetch-registry: true
    initial-instance-info-replication-interval-seconds: 30
    registry-fetch-interval-seconds: 3
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8001/register/eureka/
zuul:
  SendErrorFilter:
    error:
      disable: true
  routes:
    auth:
      path: /auth/**
      serviceId: ACHUI-Auth
      sensitiveHeaders: "*"
    system:
      path: /system/**
      serviceId: ACHUI-Server-System
      sensitiveHeaders: "*"
    test:
      path: /test/**
      serviceId: ACHUI-Server-Test
      sensitiveHeaders: "*"
  retryable: true
  ignored-services: "*"
  ribbon:
    eager-load:
      enabled: true
ribbon:
  ReadTimeout: 3000
