server:
  port: 8301
spring:
  cloud:
    gateway:
      routes:
        - id: ACHUI-Auth
          uri: lb://ACHUI-Auth
          predicates:
            - Path=/auth/**
          filters:
            - name: Hystrix
              args:
                name: authfallback
                fallbackUri: forward:/fallback/ACHUI-Auth
        - id: ACHUI-Server-System
          uri: lb://ACHUI-Server-System
          predicates:
            - Path=/system/**
          filters:
            - name: Hystrix
              args:
                name: systemfallback
                fallbackUri: forward:/fallback/ACHUI-Server-System
        - id: ACHUI-Server-test
          uri: lb://ACHUI-Server-Test
          predicates:
            - Path=/test/**
          filters:
            - name: Hystrix
              args:
                name: testfallback
                fallbackUri: forward:/fallback/ACHUI-Server-Test
      default-filters:
        - StripPrefix=1

  boot:
    admin:
      client:
        url: http://localhost:8401
        username: achui
        password: 123456

info:
  app:
    name: ${spring.application.name}
    description: "@project.description@"
    version: "@project.version@"

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
